title: <p align="center"> Naveen K V </p>
logo: /assets/img/Naveen_image.jpeg

description:
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
#   <a href="https://www.linkedin.com/in/iamlaxmikant">LinkedIn</a> |
  <a href="https://github.com/Naveenkv93">GitHub</a>
  
  <br> 
 Product Owner | Java Developer | Python | Machine Learning enthusiast | JavaScript | Automation | SAP BTP 
 
- 7+ years of experience in Software development currently working as Product Owner of S/4HANA Test Automation Tool's component
- Specialized in Java, Spring boot. Hands on experience in Python and Machine Learning
- Started as Java developer and moved into Product Owner rols over the years 
<br>
  </p>
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
